name: MicroPython

on:
  push:
  pull_request:
  release:
    types: [created]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  MICROPYTHON_VERSION: v1.18
  BUILD_TYPE: Release
  BOARD_TYPE: PICO

jobs:
  build:
    name: ${{matrix.name}}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        name: [Linux]
        cache-key: [linux]
        cmake-args: ['-DPICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk']
        apt-packages: [clang-tidy gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib cmake]

    runs-on: ${{matrix.os}}

    steps:
    # Check out MicroPython
    - name: Checkout MicroPython
      uses: actions/checkout@v2
      with:
        repository: micropython/micropython
        ref: ${{env.MICROPYTHON_VERSION}}
        submodules: false  # MicroPython submodules are hideously broken
        path: micropython

    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        submodules: true
        path: pimoroni-pico-${{ github.sha }}

    # Copy Python module files
    - name: Copy modules
      run: |
        cp -r pimoroni-pico-${GITHUB_SHA}/micropython/modules_py/* micropython/ports/rp2/modules/

    # Linux deps
    - name: Install deps
      if: runner.os == 'Linux'
      run: |
        sudo apt update && sudo apt install -y ${{matrix.apt-packages}}

    - name: Fetch base MicroPython submodules
      shell: bash
      working-directory: micropython
      run: git submodule update --init

    - name: Fetch Pico SDK submodules
      shell: bash
      working-directory: micropython/lib/pico-sdk
      run: git submodule update --init

    - name: Build mpy-cross
      shell: bash
      working-directory: micropython/mpy-cross
      run: make

    - name: Build MicroPython
      shell: bash
      working-directory: micropython/ports/rp2
      run: make USER_C_MODULES=../../../pimoroni-pico-${GITHUB_SHA}/micropython/modules/micropython.cmake -j2

    - name: Name .uf2 for artifact (release)
      if: github.event_name == 'release'
      shell: bash
      run: |
        echo "UF2_ARTIFACT_NAME=${{github.event.repository.name}}-${{github.event.release.tag_name}}-micropython-${{env.MICROPYTHON_VERSION}}.uf2" >> $GITHUB_ENV

    - name: Name .uf2 for artifact (non-release)
      if: github.event_name != 'release'
      shell: bash
      run: |
        echo "UF2_ARTIFACT_NAME=${{github.event.repository.name}}-${{github.sha}}-micropython-${{env.MICROPYTHON_VERSION}}.uf2" >> $GITHUB_ENV

    - name: Store .uf2 as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.UF2_ARTIFACT_NAME}}
        path: micropython/ports/rp2/build-${{env.BOARD_TYPE}}/firmware.uf2

    - name: Upload .uf2
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        asset_path: micropython/ports/rp2/build-${{env.BOARD_TYPE}}/firmware.uf2
        upload_url: ${{github.event.release.upload_url}}
        asset_name: ${{env.UF2_ARTIFACT_NAME}}
        asset_content_type: application/octet-stream
